# -*- coding: utf-8 -*-
"""HoneyProduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IpmcoNi5-SmVa-xXuNROBau0sg2rdrXn

## **HONEY PRODUCTION MINOR PROJECT**

Q1.Explore quantitative and qualitative variables in the dataset
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

df = pd.read_csv("/content/honeyproduction.csv") ## Saving the data into df
df.head(20)

df.state.count() ## Checking how many lines are on the dataset

yield_ = df['yieldpercol'].groupby(by=df['year']).sum() 
yield_.head()

"""Q2.Find the relationship between numerical variables using pair plots and correlation plots."""

sns.pairplot(df)

"""Q3.overall trend of the honey production in the US over the years"""

plt.figure(figsize=(15,10))
sns.lineplot(x=yield_.index,y=yield_.values,label='Yield per colony')
plt.title("Yield per colony", size=20)
plt.xlabel("Year", size=18)
plt.ylabel("Yield", size = 18)

"""Q4.Are there any patterns that can be observed between total honey production and value of production every year? How has value of production, which in some sense could be tied to demand, changed every year?"""

plt.figure(figsize=(15,10))
plt.plot(df['priceperlb'].groupby(by=df['year']).sum())
plt.title("Price per lb of honey", size=20)
plt.xlabel("Year", size = 15)
plt.ylabel("Price", size = 15)

"""We saw that the production is decreasing year by year, if the demand is the same, the price will go up. This can be seen in the above graphic"""

plt.figure(figsize=(15,10))
plt.plot(df['prodvalue'].groupby(by=df['year']).sum())
plt.title("Produced value of honey", size=20)
plt.xlabel("Year", size = 15)
plt.ylabel("Price", size = 15)

"""We see that the produced value is tied with the Yield per colony and the price per lb. When there's a decrease in Yield, but a increse in price, the price will adjust. For example, let's look into the years 2001-2003 and 2003-2005.

From 2001-2003, there was a huge increase in value. We didn't see a significant decrease in Yield, but the price skyrocket!

From 2003-2005, the price decrease (not to the same level of 2001), as well as the yield, so the produced value decrease a lot.

During the next years, we see a continous decrease of yield and a continuous increase in price per lb, but the tendency of the produced value is to always increase

---

Q5.Variation in the number of colonies over the years
"""

num_2012 = df['numcol'].loc[df['year']<2013].groupby(by=df['year']).sum() 
num_2012.head()

plt.figure(figsize=(12,10))
sns.barplot(x=num_2012.index,y=num_2012.values)
plt.title("number of colony over the years", size=20)
plt.xlabel("Year", size = 15)
plt.ylabel("number of colonies", size = 15)

"""Q6.Analyse the variation of yield per colony over the years and production trend at state level

production trend at state level
"""

state = df['totalprod'].groupby(by=df['state'], axis=0, sort=False).sum().sort_values(ascending=False)
state.head()

plt.figure(figsize=(15,10))
sns.barplot(x=state.index,y=state.values) ## Barplot is useful, when we have categories, such as state
plt.title("Statewise total production of honey in USA", size=20)
plt.xlabel("State", size=18)
plt.ylabel("Total production of honey in USA", size = 18)

state1998 = df['totalprod'].groupby(by=df['state'].loc[df['year']==1998], axis=0).sum()
state_1998 = pd.DataFrame({'State_1998':state1998.index,'Total_Produced_1998':state1998.values})
## Grouping the data and creating a dataframe with it!
state_1998.tail(10)

state2012 = df['totalprod'].groupby(by=df['state'].loc[df['year']==2012], axis=0).sum() 
state_2012 = pd.DataFrame({'State_2012':state2012.index,'Total_Produced_2012':state2012.values})
## Grouping the data and creating a dataframe with it!
state_2012.tail(10)

"""We see that there are missing states in 2012 dataset, maybed they stopped producing honey. We'll try to add them and sort by state again. We'll add these states with a value of 0."""

print(state_1998['State_1998'].unique())
print(state_2012['State_2012'].unique())

"""We are missing MD, NV, and OK"""

missing = pd.DataFrame({'State_2012':['MD','NV', 'OK'], 'Total_Produced_2012':[0,0,0]})
state_2012 = state_2012.append(missing, ignore_index=True)
state_2012.tail(10)

"""Variance of Yield per colony"""

yield_2012 = df['yieldpercol'].loc[df['year']<2013].groupby(by=df['year']).sum() 
yield_2012.head()

plt.figure(figsize=(12,9))
sns.barplot(x=yield_2012.index,y=yield_2012.values)
plt.title("Yield per colony before 1998", size=20)
plt.xlabel("Year", size = 15)
plt.ylabel("Yield", size = 15)

"""There's a strong tendency of decrease, this can be seen by plotting the data point and fitting a linear regression in it with seaborn regplot.

Q7.Declining production trend
"""

US_state_max = df[['state','totalprod']].groupby('state').max()
US_state_max.reset_index(level=0,inplace=True)
US_state_max.columns = ['State','Max Prod']
US_state_max.head()

US_state_min = df[['state','totalprod']].groupby('state').min()
US_state_min.reset_index(level=0,inplace=True)
US_state_min.columns = ['State','Min Prod']
US_state_min.head()

st_range = pd.merge(US_state_max,US_state_min,how='inner',on='State')
st_range.head()

st_range['Per_Change'] = ((st_range['Max Prod']-st_range['Min Prod'])/st_range['Max Prod'])*100
st_range.sort_values(by='Per_Change',ascending=False,inplace=True)
st_range.head()

plt.figure(figsize=(20,7))
sns.barplot(x='State',y='Per_Change',data= st_range)
plt.title('Production Decline Trend',fontsize=20)
plt.xlabel("State",fontsize=15)
plt.ylabel("% Decline",fontsize=15)

"""The Bar chart explains the states MO,NM and ME are the highest percentage of decline in the honey production. The states OR,SC and MI are lowest decline in the honey production."""